# Created using wingetcreate 1.0.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: getcomposer.org.Composer-PHPDependencyManager
PackageVersion: 6.3.0
Installers:
- Architecture: neutral
  InstallerType: inno
  InstallerUrl: https://getcomposer.org/Composer-Setup.exe
  InstallerSha256: 10826B503BA6823F14893F0627823017EE1778881222EA9960A7E268739D6956
ManifestType: installer
ManifestVersion: 1.1.0

